feat: 카테고리로 전체,디테일 조회
KU-rum/backend pull request #26
Opened 2024-11-09 04:29 UTC by Hyeri1ee

## #️⃣ 연관된 이슈

> #25 

## 📝작업 내용

> 특정 카테고리로 핀포인트 조회 기능과 학생식당, k-cube 의 경우 디테일(메뉴, 층) 정보를 조회하는 기능을 구현하였습니다. 

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> join관계가 아닌 테이블의 정보를 가져오기 위해 `BuildingSearchService`에 여러 레포지토리를 가져왔는데 괜찮나요?

2024-11-09 07:29 UTC, buzz0331 approved these changes
긴 코드 짜느라 수고 많으셨습니다 :)

2024-11-09 07:29 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/domain/building/controller/BuildingSearchController.java
> +  }
BaseResponse<List<BuildingResponse>>로 반환해주는게 좀더 명시적일 것 같습니다!

```
  @GetMapping("/{category}")
  public BaseResponse<List<BuildingResponse>> viewBuildingByCategory(@PathVariable("category") String category){
    return BaseResponse.ok(buildingSearchService.viewBuildingByCategory(category.trim()));
  }

```

2024-11-09 07:29 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/domain/building/service/BuildingSearchService.java
> +    } else {//K-CUBE..인 경우
현재 CategoryDetail이라는 Enum이 존재하니까 해당 Enum에 'isEqual()' 이라는 메서드를 만들어서 활용하는 것도 좋을 것 같아요!

2024-11-09 07:29 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/global/response/status/BaseExceptionResponseStatus.java
> +    CATEGROYNAME_NOT_EXIST(600, HttpStatus.NOT_FOUND, "존재하지 않는 카테고리명 입니다."),
CATEGORY 오타 있는 것 같습니다!

2024-11-09 07:29 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryDetail.java
아마 Category를 버튼으로 누르는 방식인 것으로 알고 있어서 대소문자 구분은 딱히 필요 없어보입니다!

그리고 편의점이나 카페 등의 카테고리도 추가해야 할 것 같아요

2024-11-12 16:52 UTC, Hyeri1ee commented on backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryDetail.java
'학생식당'의 경우, 메뉴를 디테일로 보여주고, k-cube 의 경우 층수를 디테일로 보여주는데, 편의점이나 카페의 경우에는 디테일로 어떤거를 보여주는 게 좋을까요?

2024-11-12 17:31 UTC, Hyeri1ee commented on backend/src/main/java/ku_rum/backend/domain/building/service/BuildingSearchService.java
> +    } else {//K-CUBE..인 경우
넵 반영했습니다!

2024-11-12 19:03 UTC, Hyeri1ee commented
이전 이슈 #17 리팩토링 후 테스트코드 다시 작성하였고,
해당 이슈도 리팩토링 후 테스트코드 작성 하였습니다!

2024-11-14 16:20 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryDetail.java
편의점은 층수, 카페는 메뉴+층수 이런식으로 보여주는게 좋을 것 같습니다!

2024-11-16 00:02 UTC, Hyeri1ee commented on backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryDetail.java
넵 편의점, 카페 추가하였고 테스트코드도 작성했습니다.

2024-11-17 08:33 UTC, kmw10693 approved these changes

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +        result = foundBuildingAbbrev1.get();
```
    Optional<BuildingAbbrev> result = potentialMatches.stream()
        .filter(b -> b.getName().toLowerCase().equals(finalName) || 
        b.getAbbreviation().toLowerCase().equals(finalName))
        .findFirst();

    return result.orElseThrow(() -> new BuildingNotFoundException("건물을 찾을 수 없습니다: " + name));

```

이 분은 이런식으로 수정할 수 있겠네요!

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +   // List<Long> buildingIdsFr = buildingCategoryQueryRepository.findByBuildingIds(buildingIds);
주석 지워주세요!

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/domain/Building.java
> +    }
이 메서드는 private으로 하는게 나아보입니다!

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/presentation/BuildingSearchController.java
> +  public BaseResponse<Optional<BuildingResponse>> viewBuildingByNumber(@RequestParam("number") int number) {
number가 null 값이 들어올수도 있어서, 유효성 검사 어노테이션(@Min, @NotNull 등)을 추가하는게 어떨까요?

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/presentation/BuildingSearchController.java
> +  public BaseResponse<BuildingResponse> viewBuildingByName(@RequestParam("name") String name){
name이 null 값이 들어올수도 있어서, 유효성 검사 어노테이션(@min, https://github.com/NotNull 등)을 추가하는게 어떨까요?

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryDetail.java
> +  }
isEqual을 추가하신 이유가 있을까요?  Enum은 == 연산자로 직접 비교해도 참조가 같은지 비교하기 때문에 별도의 isEqual 메소드를 만들 필요가 없을것 같아요!

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailFloorAndMenusProviding.java
> +    }
이 로직은 따로 메서드로 빼는게 나아보여요!

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailResponse.java
> +}
abstract class를 만드신 이유가 있으실까요?

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryRelatedServiceTest.java
> +            .build();
이 로직은 겹쳐서 따로 메서드를 만들어서, 인자로 넣어주면 될 것 같습니다.

2024-11-17 08:33 UTC, kmw10693 commented on backend/src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryRelatedServiceTest.java
> +    }
System.out.println 보다 log.info를 사용해보시는게 어떨까요?

2024-11-17 08:54 UTC, kmw10693 requested changes
코드 수정해주시고 머지해주세요~ 수고하셨어요!

2024-11-17 08:54 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingRepository.java
> +  Long findBuildingByNumber(long l);
long l 대신 Long number가 어떤가요?

2024-11-17 08:54 UTC, kmw10693 commented on backend/src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryRelatedServiceTest.java
> +            .build();
이 부분도 서비스 객체에서, 엔터티를 빌더로 직접 생성하는 것보다, 엔터티 내부에서 팩터리 메서드인 of나 from을 이용해서 받아오는 것이 더 나아보입니다. 엔터티 내부의 역할과 서비스 내부의 역할을 분리해야 할 것 같습니다.

2024-11-17 08:54 UTC, kmw10693 commented on backend/src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryRelatedServiceTest.java
> +            .build();
이 부분도 빌더 대신, 엔터티 내부의 팩터리 메서드를 만들어서, 반환 받아주세요.

2024-11-17 08:54 UTC, kmw10693 commented on backend/src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryRelatedServiceTest.java
> +  }
`
@Transactional
`
의 경우 각 테스트 메서드가 종료 시에 자동으로 롤백되는 과정이 있어, @AfterEach는 불필요해 보입니다.

2024-11-17 08:54 UTC, kmw10693 commented on backend/src/test/java/ku_rum/backend/domain/building/service/BuildingInfoServiceTest.java
> +            .build();
이 부분도 팩터리 메서드를 이용해서 불러와주세요.

2024-11-17 08:54 UTC, kmw10693 commented on backend/src/test/java/ku_rum/backend/domain/building/service/BuildingInfoServiceTest.java
> +            .build();
이 부분도 팩터리 메서드를 이용해서 불러와주세요!

2024-12-24 11:29 UTC, Hyeri1ee commented on backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailResponse.java
> +}
> abstract class를 만드신 이유가 있으실까요?

카페, kube, 편의점, 카페의 관련 디테일을 한번에 설정하기 위해 만들었는데, 필요없을까요?

2024-12-24 18:27 UTC, Hyeri1ee commented
넵 반영해서 수정했습니다~

2025-01-01 04:53 UTC, kmw10693 approved these changes
수고 하셨습니다 ㅎㅎ! 코드 리뷰 남겨드렸으니, Pn 규칙에 따라 봐주시면 감사하겠습니다.

2025-01-01 04:53 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +
P5: String inputName, finalName 두 개의 변수가 쓰인 이유가 있을까요?

2025-01-01 04:53 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +    }
P3:
`return name.chars()
               .filter(ch -> !Character.isDigit(ch))
               .mapToObj(ch -> String.valueOf((char) ch))
               .collect(Collectors.joining());`
이런 식으로 Stream을 사용하면 어떨까요?

2025-01-01 04:53 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +  }
P2: 이미 if문 안에 return문이 있기 때문에, else문이 필요할 것 같지 않습니다!

2025-01-01 04:53 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +    throw new CategoryNotProvidingDetail(BaseExceptionResponseStatus.CATEGORYNAME_NOT_PROVIDING_DETAIL);
```
private CategoryDetail getCategoryDetail(String category) {
    if (category == null || category.isEmpty()) { // 입력값 검증
        return null;
    }
    return Arrays.stream(CategoryDetail.values())
                 .filter(detail -> detail.getCategoryName().equals(category))
                 .findFirst()
                 .orElse(null); // 값이 없을 경우 null 반환
}
```
P4: 이런 식으로 Stream을 사용하여 나타낼 수도 있을 것 같습니다.

2025-01-01 14:15 UTC, Hyeri1ee commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +
inputName은 오류 출력시 사용되는데, 인자로 들어온 값과 동일하므로 설정하지 않아도 될 것 같습니다 수정하겠습니다

2025-01-01 14:31 UTC, Hyeri1ee commented on backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
> +    throw new CategoryNotProvidingDetail(BaseExceptionResponseStatus.CATEGORYNAME_NOT_PROVIDING_DETAIL);
넵 값이 없는 경우 정해진 오류를 출력하는 것이 좋을 것 같아 orElseThrow 로 수정하겠습니다

2025-01-01 15:00 UTC, Hyeri1ee commented
말씀하신 부분 반영해서 업데이트했습니다!

2025-01-02 04:44 UTC, merged