feat: 북마크 저장 및 조회 기능 구현
KU-rum/backend pull request #28
Opened 2024-11-10 08:32 UTC by buzz0331

## #️⃣ 연관된 이슈

> #27 

## 📝작업 내용

- 사용자가 북마크를 저장하면 북마크 테이블에 사용자의 id와 Notice 객체의 url(현재 primary key로 사용중)을 저장
- 북마크 조회를 요청이 들어오면 알맞은 사용자가 저장한 모든 공지사항을 북마크 테이블에서 찾아서 반환

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 현재 Notice 객체의 primary key를 url로 설정해놨는데 다른 좋은 방법이 있을까요?

Closes #21

2024-11-12 19:38 UTC, Hyeri1ee reviewed
테스트 코드 짜느라 수고하셨습니다.!

2024-11-12 19:38 UTC, Hyeri1ee commented on backend/src/main/java/ku_rum/backend/domain/bookmark/dto/request/BookmarkSaveRequest.java
> +    private Long userId;
지금 제가 구현한 부분도 그렇고, userId를 명시적으로 request의 필드로나 requestParam 형식으로 전달하고 있는데, accesstoken을 header에 담아 전송하는 형식으로 추후에 수정되어야 될 것 같습니다. 아직 springsecurity에 대해 저도 이해가 부족한 것 같아서 공부해 봐야겠네요 ;;

2024-11-12 19:49 UTC, Hyeri1ee commented
> > 현재 Notice 객체의 primary key를 url로 설정해놨는데 다른 좋은 방법이 있을까요?

erd 에서는 Notice 객체의 기본키를 auto increment 로 설정했던 것 같습니다.

2024-11-14 16:14 UTC, buzz0331 commented
> > > 현재 Notice 객체의 primary key를 url로 설정해놨는데 다른 좋은 방법이 있을까요?
> 
> erd 에서는 Notice 객체의 기본키를 auto increment 로 설정했던 것 같습니다.

회의에서 auto increment로 하게 되면 주기적인 크롤링시에 중복 검사가 어려워서 다른 방법을 사용하는게 좋을 것 같다는 의견이 있어서 url을 기본키로 수정하였는데 혹시 다른 의견이 있으신 분이 있나해서 여쭤보았습니다!

2024-11-14 16:18 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/dto/request/BookmarkSaveRequest.java
> +    private Long userId;
> 지금 제가 구현한 부분도 그렇고, userId를 명시적으로 request의 필드로나 requestParam 형식으로 전달하고 있는데, accesstoken을 header에 담아 전송하는 형식으로 추후에 수정되어야 될 것 같습니다. 아직 springsecurity에 대해 저도 이해가 부족한 것 같아서 공부해 봐야겠네요 ;;

저도 이 부분은 일단 찾아보면서 적어놓기는 했는데 정확히는 이해가 아직 안된 상태라.. 공부가 필요해보여요 🥲

2024-11-17 08:41 UTC, kmw10693 requested changes
코드 짜느라 고생하셨어요!

2024-11-17 08:41 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/application/BookmarkService.java
> +        Optional<User> user = userRepository.findById(bookmarkRequest.getUserId()); //예외 처리 필요?? (이미 로그인되어서 온 상태니까..)
예외처리가 필요할것 같습니다. DB에서 잘못 데이터가 저장하는 경우를 고려해서요!

2024-11-17 08:41 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/application/BookmarkService.java
> +        Optional<User> user = userRepository.findById(userId);
이것도 예외처리 처리하도록 변경해주세요!

2024-11-17 08:41 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/application/BookmarkService.java
> +        List<Bookmark> bookmarks = bookmarkRepository.findByUser(user.get());
user.get()을 쓰는것은 null 가능성이 있어서, 지양해주세요!

2024-11-17 08:41 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/domain/Bookmark.java
> +    @JoinColumn(name = "notice_url", referencedColumnName = "url", nullable = false)
referencedColumnName 왜 사용하셨는지 궁금합니다!

2024-11-17 08:41 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/dto/request/BookmarkSaveRequest.java
> +    private Long userId;
현재 userId를 필시적으로 request의 필드로 전달하는데, accessToken, refreshToken으로 사용할 수 있도록 변경하겠습니다!

2024-11-17 08:41 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/dto/request/BookmarkSaveRequest.java
> +    }
private으로 변경하더라도 @Builder를 사용할 수 있습니다!

2024-11-17 08:41 UTC, kmw10693 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/presentation/BookmarkController.java
> +    }
addBookmark 메서드에서 bookmarkRequest 객체의 유효성을 검사하는 것이 좋은 것 같습니다!
예를 들어, 필수 필드가 null인지 확인하거나, 잘못된 데이터 형식이 입력되었는지 검사할 수 있습니다.
이를 위해 @Valid 어노테이션과 @NotNull, @NotBlank 등의 검증 어노테이션을 사용할 수 있습니다!

2024-11-22 07:44 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/domain/Bookmark.java
> +    @JoinColumn(name = "notice_url", referencedColumnName = "url", nullable = false)
notice의 주키를 url로 바꿔서 이를 명시하려고 작성하였는데 삭제하겠습니다!

2024-11-22 07:46 UTC, buzz0331 commented on backend/src/main/java/ku_rum/backend/domain/bookmark/dto/request/BookmarkSaveRequest.java
> +    }
혹시 어떤걸 private으로 변경하라는 말씀이시죠..?

2024-11-22 08:13 UTC, buzz0331 commented
코드 리뷰 적용해서 수정완료했습니다!

2025-01-10 10:33 UTC, tintin010 approved these changes
수고하셨습니다!

2025-01-11 05:24 UTC, kmw10693 approved these changes
코드 짜느라 고생하셨어요~

2025-01-11 05:24 UTC, merged