docker container에 프로젝트와 redis 올리기
KU-rum/backend pull request #7
Opened 2024-09-24 13:39 UTC by Hyeri1ee

closes #6 

🤔 Describe
Dockerfile, compose.yml 파일 추가

✅ Tasks
aws에서 ec2 및 rds 설정 후 docker container 실행

🙋🏻 More
현재 aws 계정이 block 되어서 ec2 인스턴스를 생성하지 못하고 있습니다.
support에 문의해 놓은 상태입니다.

2024-09-24 21:55 UTC, kmw10693 commented
> redis와 프로젝트 관련 설정만 있는데 mysql 설정도 compose.yml에 추가해야될까요?
( 아니면 aws의 rds 에서 mysql 이 있으니까 연결 설정만 application.yml에 추가하면 될까요? )
mysql도 설정해서 docker container를 돌렸는데 프로젝트 자체가 시작하자마자 멈춰서 redis만 넣었습니다.

이미 RDS가 존재하니, mysql은 따로 compose.yml에 추가할 필요 없이, application.yml RDS 설정만 파일에 추가하면 될 것 같습니다!
(AWS 키는 외부 정보이니, 커밋 내역에 안보이게 주의해주세요!)

2024-09-25 00:11 UTC, Hyeri1ee commented
> +) mysql 설정 추가된 compose.yml 파일 공유 가능하실까요?

넵! 
**compose.yml**
```java
services:
  my-server:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy

  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10

  my-cache-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
```
**applicaation.yml**
```java
spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: my-cache-server #redis #localhost #${EC2_public_IPv4_address}
      port: 6379


server:
  port: 8080


logging:
  level:
    org.springframework.cache : trace

---
spring:
  config:
    activate:
      on-profile : dev
```
요거로 도커 실행했는데, 
![image](https://github.com/user-attachments/assets/d67ec4b7-a130-4177-8200-d7e94eb2cc15)
서버 컨테이너가 시작후 바로 종료되고, 내부 로그를 봤더니
`org.hibernate.exception.GenericJDBCException: unable to obtain isolated JDBC connection [Access denied for user 'root'@'172.28.0.4' (using password: YES)] [n/a]`
가 있었습니다. 
mysql 연동 문제인데, 해결이 잘 안되네요 😞

2024-09-25 12:27 UTC, kmw10693 commented
> > +) mysql 설정 추가된 compose.yml 파일 공유 가능하실까요?
> 
> 넵! **compose.yml**
> 
> ```java
> services:
>   my-server:
>     build: .
>     env_file:
>       - .env
>     ports:
>       - 8080:8080
>     depends_on:
>       my-db:
>         condition: service_healthy
>       my-cache-server:
>         condition: service_healthy
> 
>   my-db:
>     image: mysql
>     environment:
>       MYSQL_ROOT_PASSWORD: 1234
>       MYSQL_DATABASE: mydb
>     volumes:
>       - ./mysql_data:/var/lib/mysql
>     ports:
>       - 3306:3306
>     healthcheck:
>       test: [ "CMD", "mysqladmin", "ping" ]
>       interval: 5s
>       retries: 10
> 
>   my-cache-server:
>     image: redis
>     ports:
>       - 6379:6379
>     healthcheck:
>       test: [ "CMD", "redis-cli", "ping" ]
>       interval: 5s
>       retries: 10
> ```
> 
> **applicaation.yml**
> 
> ```java
> spring:
>   profiles:
>     default: local
>   jpa:
>     hibernate:
>       ddl-auto: update
>     show-sql: true
>   datasource:
>     url: ${dbUrl}
>     username: ${dbUsername}
>     password: ${dbPassword}
>     driver-class-name: com.mysql.cj.jdbc.Driver
>   data:
>     redis:
>       host: my-cache-server #redis #localhost #${EC2_public_IPv4_address}
>       port: 6379
> 
> 
> server:
>   port: 8080
> 
> 
> logging:
>   level:
>     org.springframework.cache : trace
> 
> ---
> spring:
>   config:
>     activate:
>       on-profile : dev
> ```
> 
> 요거로 도커 실행했는데, ![image](https://private-user-images.githubusercontent.com/108603070/370505167-d67ec4b7-a130-4177-8200-d7e94eb2cc15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjc0NDksIm5iZiI6MTcyNzI2NzE0OSwicGF0aCI6Ii8xMDg2MDMwNzAvMzcwNTA1MTY3LWQ2N2VjNGI3LWExMzAtNDE3Ny04MjAwLWQ3ZTk0ZWIyY2MxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMjI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmY4NjdmYzRjYzFmZWI1NjE1ZDYxNDVlNjc3Y2FlZGI5NmM2N2FmMWE1MjRkNTcwNDRlZGNkMTNiM2I2NmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jelRh8ji-eJNS82C4dlU1ZDgWOR1jLS_N6qt_KrlDcw) 서버 컨테이너가 시작후 바로 종료되고, 내부 로그를 봤더니 `org.hibernate.exception.GenericJDBCException: unable to obtain isolated JDBC connection [Access denied for user 'root'@'172.28.0.4' (using password: YES)] [n/a]` 가 있었습니다. mysql 연동 문제인데, 해결이 잘 안되네요 😞

https://www.inflearn.com/community/questions/1233570/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EB%A5%BC-%EC%B2%98%EC%9D%8C-%EC%8B%9C%EC%9E%91%EC%8B%9C%EC%97%90-java-sql-sqlexception-access-denied-for-user-x27-root-x27-x?srsltid=AfmBOoqYIrMfsyx-ad6uQPWroPXrtFE7Yk-aCFj97saKD2vtti_d5Rde

계정 권한이 아마 도커에 적용이 안된 것 같은데, 위에 링크 보고 따라해보시겠어요?

2024-09-25 15:31 UTC, Hyeri1ee commented
> 계정 권한이 아마 도커에 적용이 안된 것 같은데, 위에 링크 보고 따라해보시겠어요?

![image](https://github.com/user-attachments/assets/a4009701-97c0-4381-8041-64360d919f8e)
1234로 설정했는데, 비밀번호를 올바르게 쳐도 access denied 가 뜨네요

2024-09-25 23:34 UTC, Hyeri1ee commented
해결했습니당 :)
![image](https://github.com/user-attachments/assets/412975ab-df2e-4540-a2b2-a7b6ca35239d)
application.yml에서
`dialect: org.hibernate.dialect.MySQLDialect` 이 부분을 넣어주니 연결이 되네요! 정상 작동합니다

2024-09-26 12:12 UTC, kmw10693 commented
> 해결했습니당 :) ![image](https://private-user-images.githubusercontent.com/108603070/370923024-412975ab-df2e-4540-a2b2-a7b6ca35239d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTMwMDIsIm5iZiI6MTcyNzM1MjcwMiwicGF0aCI6Ii8xMDg2MDMwNzAvMzcwOTIzMDI0LTQxMjk3NWFiLWRmMmUtNDU0MC1hMmIyLWE3YjZjYTM1MjM5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxMjExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTNjOWU0YzUwNTA1ZWJjNzkzYjEwNGQ4ZDc1NzlmZmY4MTJjNjk0NDE5ZjhmZjQ4NGIwODA1MWIxNzlkNDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CKgjfPKam4qqmiLl0m2U75m8QyX12jEDIp2yFpG5rLE) application.yml에서 `dialect: org.hibernate.dialect.MySQLDialect` 이 부분을 넣어주니 연결이 되네요! 정상 작동합니다
> 
> aws 인스턴스 하나 만들어서 올릴까요?

네네 그래주시면 될것 같습니다 고생하셨어요! ㅎㅎ

2024-09-26 12:17 UTC, kmw10693 approved these changes
레디스 및 도커 설정 하시느라 고생하셨어요~ 승인하겠습니다!

2024-09-26 12:17 UTC, kmw10693 commented on backend/build.gradle
> +
공백을 빼주세요!

2024-09-26 12:17 UTC, kmw10693 commented on backend/src/main/resources/application.yml
application.yml 도 .gitignore에 추가해주실 수 있을까요?

2024-09-26 12:19 UTC, kmw10693 requested changes
브랜치 이름을 feature/#6 으로 변경 가능하실까요? 이슈번호로 관리하면 편할것 같네요!

2024-09-26 13:30 UTC, tintin010 approved these changes
로컬에서 서버 실행 시 도커 이미지까지 생성되는건지 궁금합니다!
그리고 캐시 서버라는건 어떤건지도 궁금합니다!

2024-09-26 15:07 UTC, buzz0331 approved these changes
설정하시느라 수고많으셨습니다~ 저는 더이상 수정사항은 보이진 않는 것 같습니다!

2024-09-27 03:29 UTC, Hyeri1ee commented
> 브랜치 이름을 feature/#6 으로 변경 가능하실까요? 이슈번호로 관리하면 편할것 같네요!

[원격 저장소 이름 변경](https://you9010.tistory.com/131) 원격 저장소 이름 변경이 기본 브랜치를 삭제하고 다른 새로운 브랜치를 올리는 건데, 기존 브랜치에서 PR 보낸거는 유지가 되나요? 아니면 새로운 브랜치에서 다시 PR 보내라는 말씀이신가요 ?

2024-09-27 03:35 UTC, kmw10693 commented
> > 브랜치 이름을 feature/#6 으로 변경 가능하실까요? 이슈번호로 관리하면 편할것 같네요!
> 
> [원격 저장소 이름 변경](https://you9010.tistory.com/131) 원격 저장소 이름 변경이 기본 브랜치를 삭제하고 다른 새로운 브랜치를 올리는 건데, 기존 브랜치에서 PR 보낸거는 유지가 되나요? 아니면 새로운 브랜치에서 다시 PR 보내라는 말씀이신가요 ?

브랜치 이름을 변경하면 다시 PR을 보내야 하는군요! 그러면 이번에만 머지해도 될것 같습니다!

2024-09-27 03:35 UTC, kmw10693 approved these changes

2024-09-27 03:42 UTC, Hyeri1ee commented
> 로컬에서 서버 실행 시 도커 이미지까지 생성되는건지 궁금합니다! 그리고 캐시 서버라는건 어떤건지도 궁금합니다!

**mysql**과 **redis**는 `image:` 에 정의된 도커허브에서 내려받은 이미지를 기반으로 도커 컨테이너를 만들고, 스프링부트 프로젝트는 Dockerfile을 바탕으로 빌드된 jar를 이용한 이미지로 컨테이너를 만들어 구동시킵니다! `docker compose up -d`를 하시면, 결론적으로 이미지가 만들어져 도커 컨테이너들이 구동됩니다.

**캐시**는 원본 저장소보다 빠르게 가져올 수 있는 임시 데이터 저장소로, 캐싱(캐시를 이용해서 데이터 조회)을 하면, 캐시에서 데이터를 확인하고, 없다면 DB를 통해 조회해오는 방식이여서 더 빠르게 데이터를 조회할 수 있습니다. 

설명이 부족하지만, 답변이 되었으면 좋겠습니다

2024-09-27 03:46 UTC, Hyeri1ee commented on backend/src/main/resources/application.yml
넵 추가했습니다

2024-09-27 03:47 UTC, Hyeri1ee commented on backend/build.gradle
> +
넵 뺐습니다!

2024-09-27 03:47 UTC, merged